accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/<slug:slug>/', views.profile, name='profile'),
    path('profile/edit/<slug:slug>/', views.edit_profile, name='edit_profile'),
    path('author/<slug:slug>/', views.author_page, name='author_page'),
]

blogapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('search/', views.search_posts, name='search'),
    path('about/', views.about, name='about'),
    path('all_posts/', views.all_posts, name='all_posts'),
    path('author_all_posts/<slug:slug>/', views.author_all_posts, name='author_all_posts'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('post/<slug:slug>/update/', views.update_post, name='update_post'),
    path('post/<slug:slug>', views.post_page, name='post_page'),
    path('post/<slug:slug>/delete/', views.delete_post, name='delete_post'),
    path('tag/<slug:slug>', views.tag_page, name='tag_page'),
    path('tag/all_posts/<slug:slug>', views.tag_all_posts, name='tag_all_posts'),
    path('bookmark_post/<slug:slug>', views.bookmark_post, name='bookmark_post'),
    path('like_post/<slug:slug>', views.like_post, name='like_post'),
    path('all_bookmarked_posts/', views.all_bookmarked_posts, name='all_bookmarked_posts'),
    path('all_liked_posts/', views.all_liked_posts, name='all_liked_posts'),
]

accounts/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(null=True, blank=True, upload_to="images/")
    slug = models.SlugField(max_length=200, unique=True)
    bio = models.CharField(null=True, blank=True, max_length=200)
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.user.username)
        return super(Profile, self).save(*args, **kwargs)
    
    def full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'
    
    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class NewUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "first_name", "last_name")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Enter Username'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Repeat password'

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        new = User.objects.filter(username=username)
        if new.exists():
            raise forms.ValidationError("User already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        new = User.objects.filter(email=email)
        if new.exists():
            raise forms.ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email'] 
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email',
        }

    bio = forms.CharField(max_length=200, required=False, label='Bio')
    profile_image = forms.ImageField(required=False, label='Profile Image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set initial values for additional fields
        if self.instance.profile:
            self.fields['bio'].initial = self.instance.profile.bio
            self.fields['profile_image'].initial = self.instance.profile.profile_image

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            if hasattr(user, 'profile'):
                profile = user.profile
            else:
                profile = Profile(user=user)
            profile.bio = self.cleaned_data['bio']
            profile.profile_image = self.cleaned_data['profile_image']
            profile.save()
        return user

accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import NewUserForm, EditProfileForm
from .models import Profile
from posts.models import Post
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count


# Create your views here.
def register_user(request):
    form = NewUserForm()
    profile = None
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = Profile.objects.create(user=user)
            login(request, user)
            return redirect("/")
    
    context={'form': form, 'profile':profile}
    return render(request, 'accounts/registration.html', context)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            # Authentication failed
            error_message = 'Invalid username or password'
            return render(request, 'accounts/login.html', {'error_message': error_message})
    else:
        return render(request, 'accounts/login.html')


def user_logout(request):
    logout(request)
    return redirect('login')


@login_required
def profile(request, slug):
    posts = Post.objects.filter(author=request.user)
    top_posts = Post.objects.filter(author = request.user).order_by('-view_count')[0:2]
    recent_posts = Post.objects.filter(author = request.user).order_by('-last_updated')[0:2]
    top_authors = User.objects.annotate(number=Count('post')).order_by('-number')[0:2]

    context = {
        'user': request.user,
        'posts': posts,
        'top_posts': top_posts,
        'recent_posts': recent_posts,
        'top_authors':top_authors,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def edit_profile(request, slug):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile', slug=slug)
    else:
        form = EditProfileForm(instance=request.user)
    
    return render(request, 'accounts/edit_profile.html', {'form': form})


def author_page(request, slug):
    profile = Profile.objects.get(slug=slug)
    top_posts = Post.objects.filter(author = profile.user).order_by('-view_count')[0:2]
    recent_posts = Post.objects.filter(author = profile.user).order_by('-last_updated')[0:2]
    top_authors = User.objects.annotate(number=Count('post')).order_by('-number')[0:2]
    
    context = {
        'profile':profile, 
        'top_posts':top_posts, 
        'recent_posts':recent_posts, 
        'top_authors':top_authors,
    }
    return render(request, 'accounts/author.html', context)

accounts/templates/accounts/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blog | {{profile.full_name}}{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="layout">
          <!-- left layout -->
          <div class="left">
            <div class="page-top">
              <div class="top flex">
                <div class="page-name">
                  <a href="#" class="learn" onclick="window.history.back()">
                    <span class="material-icons"> keyboard_return </span> Go
                    back
                  </a>
                  <h1>Author</h1>
                </div>
              </div>
            </div>

            <center>
              <div class="typo">
                <h1 class="title">{{profile.full_name}}</h1>
                <p>
                  {{profile.bio}}
                </p>
              </div>
            </center>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Top posts</h1>
                <div class="grid-2 blog">
                  <!-- card -->
                  {% for post in top_posts %}
                    <a href="{% url "post_page" post.slug %}">
                      <div class="card">
                        <div class="post-img">
                          <img src="{{post.image.url}}" alt="" />
                          <div class="tag">{{post.tags.all.0.name}}</div>
                        </div>
                        <div class="card-content">
                          <h3>
                            {{post.title}}
                          </h3>
                          <div class="author">
                            <div class="profile-pic">
                              {% if post.author.profile.profile_image %}
                              <img src="{{post.author.profile.profile_image.url}}" alt="" />
                              {% else %}
                              <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                              {% endif %}
                            </div>
                            <div class="details">
                              <p>{{post.author.profile.full_name}}</p>
                              <small>{{post.last_updated|date}}</small>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                    {% empty %}
                    <p>Nothing to show here</p>
                  {% endfor %}
                  <!-- card end-->
                </div>
              </div>
            </section>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Recent Posts</h1>
                <div class="grid-3 blog-grid">
                  {% for post in recent_posts %}
                    <!-- card -->
                    <a href="{% url "post_page" post.slug %}">
                      <div class="card">
                        <div class="post-img">
                          <img src="{{post.image.url}}" alt="" />
                          <div class="tag">{{post.tags.all.0.name}}</div>
                        </div>
                        <div class="card-content">
                          <h3>
                            {{post.title}}
                          </h3>
                          <div class="author">
                            <div class="profile-pic">
                              {% if post.author.profile.profile_image %}
                              <img src="{{post.author.profile.profile_image.url}}" alt="" />
                              {% else %}
                              <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                              {% endif %}
                            </div>
                            <div class="details">
                              <p>{{post.author.profile.full_name}}</p>
                              <small>{{post.last_updated|date}}</small>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                    <!-- card end-->
                    {% empty %}
                    <p>Nothing to show here</p>
                  {% endfor %}
                </div>
                <center>
                  <a href="{% url "author_all_posts" profile.slug %}"><button class="btn btn-primary rounded view">
                  View more <span class="material-icons"> trending_flat </span>
                  </button></a>
                </center>
              </div>
            </section>
          </div>
          <!-- left layout end -->

          <!-- right layout -->
          <div class="right">
            <div class="block">
              <div class="user-profile" style="margin-bottom:20px;">
                {% if profile.profile_image %}
                  <img src="{{ profile.profile_image.url }}" alt="Profile Image">
                {% else %}
                  <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                {% endif %}
              </div>
              <h2 class="title2">Top Authors</h2>
              {% for author in top_authors %}
              <div class="recent-post other-author">
                <div class="rounded-img">
                  {% if author.profile.profile_image %}
                  <img src="{{author.profile.profile_image.url}}" alt="" />
                  {% else %}
                  <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                  {% endif %}
                </div>
                <div class="recent-content">
                  <h3>
                    {{author.profile.full_name}}
                  </h3>
                  <a class="learn" href="{% url "author_page" author.profile.slug %}"
                    >Learn more
                    <span class="material-icons"> trending_flat </span></a
                  >
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <!-- right layout end -->
        </div>
      </div>
    </main>
{% endblock content %}

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock title %}

{% block content %}
<main>
    <div class="container">
        <div class="page-name">
            <a href="{% url 'profile' user.profile.slug %}" class="learn">
                <span class="material-icons">keyboard_return</span> Go back
            </a>
            <h1>Edit Profile</h1>
        </div>

        <div class="form" style="font-size: 18px; font-weight:bold;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Render username and bio fields -->
                <div class="form-group">
                    <label for="id_first_name">First Name:</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name:</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="id_bio">Bio:</label>
                    {{ form.bio }}
                </div>
                <div class="form-group">
                    <label for="id_profile_image">Profile Image:</label>
                    {{ form.profile_image }}
                </div>
                <!-- Exclude email field -->
                <input type="hidden" name="email" value="{{ user.email }}">


                <button type="submit" class="btn btn-primary rounded">Update Profile</button>
            </form>
        </div>
    </div>
</main>
{% endblock content %}

accounts/templates/accounts/logged_out.html
{% extends "base.html" %}
{% block title %}Blog | Logged out{% endblock title %}

{% block content %}
    <main>
      <div class="container">
          <center>
              <div class="typo">
                <p> You have been successfully logged out. <a href="{% url "login" %}">Login again</a></p>
              </div>
          </center>
      </div>
    </main>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}Blog | Login{% endblock title %}

{% block content %}
    <main>
        <form action="{% url "login" %}" method="post" class="form">
            {% csrf_token %}
                <center>
                    <div class="logo f-logo">
                        <i class="fa-brands fa-blogger"></i>
                    </div>

                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <div class="field-error">
                                <p>{{error}}</p>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <div class="inputs">
                        <div class="search-bar s-active input">
                          <input type="text" placeholder="Username" name="username">
                          <div class="animated-search">
                            <i class="uil uil-user"></i>
                          </div>
                        </div>
                        <div class="search-bar s-active input">
                          <input type="password" placeholder="Password" name="password">
                          <div class="animated-search">
                            <i class="uil uil-key-skeleton"></i>
                          </div>
                        </div>
                                      
                        <button class="btn btn-primary rounded" type="submit">
                          Login <span class="material-icons"> arrow_right_alt </span>
                        </button>
                        <p>Not have an account? <a href={% url "register" %}>Sign up</a></p>
                    </div>
                </center>
        </form>
    </main>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blog | {{user.profile.full_name}}{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="layout">
          <!-- left layout -->
          <div class="left">
            <div class="page-top">
              <div class="top flex">
                <div class="page-name">
                  <a href="#" class="learn" onclick="window.history.back()">
                    <span class="material-icons"> keyboard_return </span> Go
                    back
                  </a>
                  <h1>Profile</h1>
                </div>
              </div>
            </div>

            <center>
              <div class="typo">
                <h1 class="title">{{user.profile.full_name}}</h1>
                <p>
                  {{user.profile.bio}}
                </p>
              </div>
              <div class="action-btn-container">
                <div class="action-btn">
                  <a href="{% url 'create_post' %}" class="btn btn-primary rounded">Create Post</a>
                  <a href="{% url 'edit_profile' user.profile.slug %}" class="btn btn-secondary rounded">Edit Profile</a>
                </div>
              </div>
            </center>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Top posts</h1>
                <div class="grid-2 blog">
                  <!-- card -->
                  {% for post in top_posts %}
                    <a href="{% url "post_page" post.slug %}">
                      <div class="card">
                        <div class="post-img">
                          <img src="{{post.image.url}}" alt="" />
                          <div class="tag">{{post.tags.all.0.name}}</div>
                        </div>
                        <div class="card-content">
                          <h3>
                            {{post.title}}
                          </h3>
                          <div class="author">
                            <div class="profile-pic">
                              {% if post.author.profile.profile_image %}
                              <img src="{{post.author.profile.profile_image.url}}" alt="" />
                              {% else %}
                              <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                              {% endif %}
                            </div>
                            <div class="details">
                              <p>{{post.author.profile.full_name}}</p>
                              <small>{{post.last_updated|date}}</small>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                    {% empty %}
                    <p>Nothing to show here</p>
                  {% endfor %}
                  <!-- card end-->
                </div>
              </div>
            </section>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Recent Posts</h1>
                <div class="grid-3 blog-grid">
                  {% for post in recent_posts %}
                    <!-- card -->
                    <a href="{% url "post_page" post.slug %}">
                      <div class="card">
                        <div class="post-img">
                          <img src="{{post.image.url}}" alt="" />
                          <div class="tag">{{post.tags.all.0.name}}</div>
                        </div>
                        <div class="card-content">
                          <h3>
                            {{post.title}}
                          </h3>
                          <div class="author">
                            <div class="profile-pic">
                              {% if post.author.profile.profile_image %}
                              <img src="{{post.author.profile.profile_image.url}}" alt="" />
                              {% else %}
                              <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                              {% endif %}
                            </div>
                            <div class="details">
                              <p>{{post.author.profile.full_name}}</p>
                              <small>{{post.last_updated|date}}</small>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                    <!-- card end-->
                    {% empty %}
                    <p>Nothing to show here</p>
                  {% endfor %}
                </div>
                <center>
                  <a href="{% url "author_all_posts" user.profile.slug %}"><button class="btn btn-primary rounded view">
                  View more <span class="material-icons"> trending_flat </span>
                  </button></a>
                </center>
              </div>
            </section>
          </div>
          <!-- left layout end -->

          <!-- right layout -->
          <div class="right">
            <div class="block">
              <div class="user-profile" style="margin-bottom:20px;">
                {% if user.profile.profile_image %}
                  <img src="{{ user.profile.profile_image.url }}" alt="Profile Image">
                {% else %}
                  <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                {% endif %}
              </div>
              <h2 class="title2">Top Authors</h2>
              {% for author in top_authors %}
              <div class="recent-post other-author">
                <div class="rounded-img">
                  {% if author.profile.profile_image %}
                  <img src="{{author.profile.profile_image.url}}" alt="" />
                  {% else %}
                  <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                  {% endif %}
                </div>
                <div class="recent-content">
                  <h3>
                    {{author.profile.full_name}}
                  </h3>
                  <a class="learn" href="{% url "author_page" author.profile.slug %}"
                    >Learn more
                    <span class="material-icons"> trending_flat </span></a
                  >
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <!-- right layout end -->
        </div>
      </div>
    </main>
{% endblock content %}

accounts/templates/accounts/registration.html
<!-- registration.html -->
{% extends "base.html" %}
{% block title %}Blog | Registration{% endblock title %}

{% block content %}
<main>
    <div class="container">
        <div class="page-name">
            <a href="#" class="learn" onclick="window.history.back()">
                <span class="material-icons"> keyboard_return </span> Go back
            </a>
            <h1>Sign Up</h1>
        </div>

        <form method="post" class="form">
            {% csrf_token %}
            <center>
              <div class="logo f-logo">
                  <i class="fa-brands fa-blogger"></i>
              </div>

              {% if form.non_field_errors %}
              {% for error in form.non_field_errors %}
              <div class="field-error">
                  <p>{{error}}</p>
              </div>
              {% endfor %}
              {% endif %}
              <div class="inputs">
                <div>
                  <div class="search-bar s-active input">
                    {{form.first_name}}
                    <div class="animated-search">
                        <i class="uil uil-user"></i>
                    </div>
                  </div>
                </div>

                <div>
                  <div class="search-bar s-active input">
                    {{form.last_name}}
                    <div class="animated-search">
                        <i class="uil uil-user"></i>
                    </div>
                  </div>
                </div>
                <div>
                    <div class="search-bar s-active input">
                        {{form.username}}
                        <div class="animated-search">
                            <i class="uil uil-user"></i>
                        </div>
                    </div>
                    {% if form.username.errors %}
                    <div class="field-error">
                        <p>{{form.username.errors.as_text}}</p>
                    </div>
                    {% endif %}
                </div>

                <div>
                    <div class="search-bar s-active input">
                        {{form.email}}
                        <div class="animated-search">
                            <i class="uil uil-envelope-alt"></i>
                        </div>
                    </div>

                    {% if form.email.errors %}
                    <div class="field-error">
                        <p>{{form.email.errors.as_text}}</p>
                    </div>
                    {% endif %}
                </div>


                <div>
                    <div class="search-bar s-active input">
                        {{form.password1}}
                        <div class="animated-search">
                            <i class="uil uil-key-skeleton"></i>
                        </div>
                    </div>
                    {% if form.password.errors %}
                    <div class="field-error">
                        <p>{{form.password.errors.as_text}}</p>
                    </div>
                    {% endif %}
                </div>
                <div>
                    <div class="search-bar s-active input">
                        {{form.password2}}
                        <div class="animated-search">
                            <i class="uil uil-key-skeleton"></i>
                        </div>
                    </div>
                    {% if form.password2.errors %}
                    <div class="field-error">
                        <p>{{form.password2.errors.as_text}}</p>
                    </div>
                    {% endif %}
                </div>
                <button class="btn btn-primary rounded">
                    SIGN UP <span class="material-icons"> arrow_right_alt </span>
                </button>
                <center>
                    <p>Already have an account? <a href="login.html">Login</a></p>
                </center>
              </div>
            </center>
        </form>
    </div>
</main>
{% endblock content %}