blogapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('search/', views.search_posts, name='search'),
    path('about/', views.about, name='about'),
    path('all_posts/', views.all_posts, name='all_posts'),
    path('author_all_posts/<slug:slug>/', views.author_all_posts, name='author_all_posts'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('post/<slug:slug>/update/', views.update_post, name='update_post'),
    path('post/<slug:slug>', views.post_page, name='post_page'),
    path('post/<slug:slug>/delete/', views.delete_post, name='delete_post'),
    path('tag/<slug:slug>', views.tag_page, name='tag_page'),
    path('tag/all_posts/<slug:slug>', views.tag_all_posts, name='tag_all_posts'),
    path('bookmark_post/<slug:slug>', views.bookmark_post, name='bookmark_post'),
    path('like_post/<slug:slug>', views.like_post, name='like_post'),
    path('all_bookmarked_posts/', views.all_bookmarked_posts, name='all_bookmarked_posts'),
    path('all_liked_posts/', views.all_liked_posts, name='all_liked_posts'),
]

posts/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

class Subscribe(models.Model):
    email = models.EmailField(max_length=100)
    date = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        return super(Tag, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    last_updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    tags = models.ManyToManyField(Tag, blank=True, related_name='post')
    view_count = models.IntegerField(null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    bookmarks = models.ManyToManyField(User, related_name="bookmarks", default=None, blank=True)
    likes = models.ManyToManyField(User, related_name="likes", default=None, blank=True)
    
    def number_of_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return self.title

class Comments(models.Model):
    content = models.TextField()
    date = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.DO_NOTHING, null=True, blank=True, related_name='replies')

class WebsiteMeta(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    about = models.TextField()

posts/forms.py
from django import forms
from .models import Post, Tag, Comments, Subscribe
from django.utils.translation import gettext_lazy as _


class PostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple())
    
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'tags']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['content', 'email', 'name']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].widget.attrs['placeholder'] = 'Type your comment....'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['name'].widget.attrs['placeholder'] = 'Name'
        self.fields['email'].widget.attrs['class'] = 'user-input'
        self.fields['name'].widget.attrs['class'] = 'user-input'


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = '__all__'
        labels = {'email':_('')}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'Enter your email'

posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .forms import PostForm, CommentForm
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils.text import slugify
from .models import Comments, Post, Tag
from django.contrib.auth.models import User
from django.db.models import Count

# Create your views here.

@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            base_slug = slugify(post.title)
            slug = base_slug
            counter = 1
            while Post.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            post.slug = slug
            post.save()
            form.save_m2m()
            return redirect('post_page', slug=post.slug)
    else:
        form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def update_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.user != post.author:
        return HttpResponseForbidden("You are not authorized to perform this action.")
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('post_page', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'posts/edit_post.html', {'form': form})


@login_required
def delete_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.user != post.author:
        return HttpResponseForbidden("You are not authorized to perform this action.")
    if request.method == 'POST':
        post.delete()
        return redirect('profile')
    return render(request, 'posts/delete_post.html', {'post': post})


def post_page(request, slug):
    post = Post.objects.get(slug = slug)
    comments = Comments.objects.filter(post=post, parent=None)
    form = CommentForm()
    comment_count = comments.count()
    # Bookmark logic
    bookmarked = False
    if post.bookmarks.filter(id = request.user.id).exists():
        bookmarked = True
    is_bookmarked = bookmarked
    
    # Liked logic
    liked = False
    if post.likes.filter(id = request.user.id).exists():
        liked = True
    number_of_likes = post.number_of_likes()
    is_liked = liked
    
    if request.POST:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            parent_obj = None
            if request.POST.get('parent'):
                parent = request.POST.get('parent')
                parent_obj = Comments.objects.get(id=parent)
                if parent_obj:
                    comment_reply = comment_form.save(commit=False)
                    comment_reply.parent = parent_obj
                    comment_reply.post = post
                    comment_reply.save()
                    return HttpResponseRedirect(reverse('post_page', kwargs={'slug':slug})) 
            else:
                comment = comment_form.save(commit=False)
                postid = request.POST.get('post_id')
                post = Post.objects.get(id = postid)
                comment.post = post
                comment.save()
                return HttpResponseRedirect(reverse('post_page', kwargs={'slug':slug}))
            
    if request.method != 'POST':
        if post.view_count is None:
            post.view_count = 1
        else:
            post.view_count += 1
        post.save(update_fields=['view_count'])
    
    # sidebar
    recent_posts = Post.objects.exclude(id=post.id).order_by('-last_updated')[0:2]
    top_authors = User.objects.annotate(number = Count('post')).order_by('-number')[0:2]
    tags = Tag.objects.all()
    related_posts = Post.objects.exclude(id=post.id).filter(author=post.author)[0:2]
    
    context = {
        'post':post, 
        'form':form, 
        'comments':comments, 
        'is_bookmarked':is_bookmarked, 
        'is_liked':is_liked, 
        'number_of_likes':number_of_likes, 
        'recent_posts':recent_posts, 
        'top_authors':top_authors, 
        'tags':tags, 
        'related_posts':related_posts,
        'comment_count':comment_count,
    }
    
    return render(request, 'posts/post.html', context)


def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    top_posts = Post.objects.filter(tags__in=[tag.id]).order_by('-view_count')[0:2]
    recent_posts = Post.objects.filter(tags__in=[tag.id]).order_by('-last_updated')[0:2]
    tags = Tag.objects.all()
    
    context = {
        'tag':tag, 
        'top_posts':top_posts, 
        'recent_posts':recent_posts, 
        'tags':tags
    }
    return render(request, 'posts/tag.html', context)


def tag_all_posts(request, slug):
    tag = Tag.objects.get(slug=slug)
    all_posts = Post.objects.filter(tags__in=[tag.id])
    
    context = {
        'tag' : tag,
        'all_posts': all_posts
    }
    
    return render(request, 'posts/tag_all_posts.html', context)

def bookmark_post(request, slug):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.bookmarks.filter(id = request.user.id).exists():
        post.bookmarks.remove(request.user)
    else:
        post.bookmarks.add(request.user)
    return HttpResponseRedirect(reverse('post_page', args=[str(slug)]))


def like_post(request, slug):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id = request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return HttpResponseRedirect(reverse('post_page', args=[str(slug)]))


def all_bookmarked_posts(request):
    all_bookmarked_posts = Post.objects.filter(bookmarks=request.user)
    
    context={
        'all_bookmarked_posts':all_bookmarked_posts
    }
    
    return render(request, 'posts/all_bookmarked_posts.html', context)


def all_liked_posts(request):
    all_liked_posts = Post.objects.filter(likes=request.user)
    
    context={
        'all_liked_posts':all_liked_posts
    }
    
    return render(request, 'posts/all_liked_posts.html', context)

posts/templates/posts/about.html
{% extends "base.html" %}
{% block title %}Blog | About{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="#" class="learn" onclick="window.history.back()">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>About</h1>
            </div>
          </div>
        </div>
      </div>
      <div style="margin: 40px 40px;">
        <div class="bolg-post" style="margin-left: 40px;">
          <div class="blog-post-content">
            <p>
              {{website_info.about|safe}}
            </p>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

posts/templates/posts/all_bookmarked_posts.html
{% extends "base.html" %} 
{% block title %}Blog | Bookmarked Posts{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="{% url "index" %}" class="learn" onclick="window.history.back()">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>Bookmarked Posts</h1>
            </div>
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
        <div class="blog-tags">
          {% for post in all_bookmarked_posts %}
          <p class="tag">
            <a style="color: white;" href="{% url "post_page" post.slug %}">{{post.title}}</a>
          </p>
          {% endfor %} 
        </div>
      </div>
    </section>
{% endblock content %}

posts/templates/posts/all_liked_posts.html
{% extends "base.html" %} 
{% block title %}Blog | All Liked Posts{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="{% url "index" %}" class="learn" onclick="window.history.back()">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>All Posts</h1>
            </div>
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
        <div class="blog-tags">
          {% for post in all_liked_posts %}
          <p class="tag">
            <a style="color: white;" href="{% url "post_page" post.slug %}">{{post.title}}</a>
          </p>
          {% endfor %} 
        </div>
      </div>
    </section>
{% endblock content %}

posts/templates/posts/all_posts.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blog | Search{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="#" class="learn" onclick="window.history.back()">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>All Posts</h1>
            </div>
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
        <div class="grid">
          <!-- card -->
          {% for post in posts %}
          <a href="{% url "post_page" post.slug %}">
            <div class="card">
              <div class="post-img">
                <img src="{{post.image.url}}" alt="" />
                {% if post.tags.all %}
                <div class="tag">{{ post.tags.all.0.name }}</div>
                {% endif %}
              </div>
              <div class="card-content">
                <h3>{{ post.title }}</h3>
                <div class="author">
                  <div class="profile-pic">
                    {% if post.author.profile.profile_image %}
                    <img src="{{post.author.profile.profile_image.url}}" alt="" />
                    {% else %}
                    <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                    {% endif %}
                  </div>
                  <div class="details">
                    <p>{{ post.author.profile.full_name }}</p>
                    <small>{{ post.last_updated|date }}</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
          {% endfor %}
          <!-- card end-->
        </div>
      </div>
    </section>

    <!-- Pagination -->
    <div class="container">
      <div class="pagination">
        {% if posts.has_previous %}
          <a href="?page=1">&laquo;</a>
          <a href="?page={{ posts.previous_page_number }}">{{ posts.previous_page_number }}</a>
        {% endif %}
        
        <span class="current">{{ posts.number }}</span>

        {% if posts.has_next %}
          <a href="?page={{ posts.next_page_number }}">{{ posts.next_page_number }}</a>
          <a href="?page={{ posts.paginator.num_pages }}">&raquo;</a>
        {% endif %}
      </div>
    </div>
{% endblock content %}

posts/templates/posts/author.html
{% extends "base.html" %}
{% block title %}Blog | {{profile.user.first_name}}{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="layout">
          <!-- left layout -->
          <div class="left">
            <div class="page-top">
              <div class="top flex">
                <div class="page-name">
                  <a href="#" class="learn" onclick="window.history.back()">
                    <span class="material-icons"> keyboard_return </span> Go
                    back
                  </a>
                  <h1>Author</h1>
                </div>
              </div>
            </div>

            <center>
              <div class="typo">
                <h1 class="title">{{profile.user.first_name}}</h1>
                <p>
                  {{profile.bio}}
                </p>
              </div>
            </center>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Top posts</h1>
                <div class="grid-2 blog">
                  <!-- card -->
                  {% for post in top_posts %}
                    <a href="{% url "post_page" post.slug %}">
                      <div class="card">
                        <div class="post-img">
                          <img src="{{post.image.url}}" alt="" />
                          <div class="tag">{{post.tags.all.0.name}}</div>
                        </div>
                        <div class="card-content">
                          <h3>
                            {{post.title}}
                          </h3>
                          <div class="author">
                            <div class="profile-pic">
                              <img src="{{profile.profile_image.url}}" alt="" />
                            </div>
                            <div class="details">
                              <p>{{post.author.first_name}}</p>
                              <small>{{post.last_updated|date}}</small>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                    {% empty %}
                    <p>Nothing to show here</p>
                  {% endfor %}
                  <!-- card end-->
                </div>
              </div>
            </section>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Recent Posts</h1>
                <div class="grid-3 blog-grid">
                  {% for post in recent_posts %}
                    <!-- card -->
                    <a href="{% url "post_page" post.slug %}">
                      <div class="card">
                        <div class="post-img">
                          <img src="{{post.image.url}}" alt="" />
                          <div class="tag">{{post.tags.all.0.name}}</div>
                        </div>
                        <div class="card-content">
                          <h3>
                            {{post.title}}
                          </h3>
                          <div class="author">
                            <div class="profile-pic">
                              <img src="{{post.author.profile.profile_image.url}}" alt="" />
                            </div>
                            <div class="details">
                              <p>{{post.author.first_name}}</p>
                              <small>{{post.last_updated|date}}</small>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                    <!-- card end-->
                    {% empty %}
                    <p>Nothing to show here</p>
                  {% endfor %}
                </div>
                <center>
                  <button class="btn btn-primary rounded view">
                    View more
                    <span class="material-icons"> trending_flat </span>
                  </button>
                </center>
              </div>
            </section>
          </div>
          <!-- left layout end -->

          <!-- right layout -->
          <div class="right">
            <div class="block">
              <h2 class="title2">Top Authors</h2>
              {% for author in top_authors %}
              <div class="recent-post other-author">
                <div class="rounded-img">
                  <img src="{{author.profile.profile_image.url}}" alt="" />
                </div>
                <div class="recent-content">
                  <h3>
                    {{author.first_name}}
                  </h3>
                  <a class="learn" href="{% url "author_page" author.profile.slug %}"
                    >Learn more
                    <span class="material-icons"> trending_flat </span></a
                  >
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <!-- right layout end -->
        </div>
      </div>
    </main>
{% endblock content %}

posts/templates/posts/author_all_posts.html
{% extends "base.html" %} 
{% block title %}Blog | Posts by {{profile.full_name}}{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="#" class="learn" onclick="window.history.back()">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>Posts by {{profile.full_name}}</h1>
            </div>
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
        <div class="blog-tags">
          {% for post in all_posts %}
          <p class="tag">
            <a style="color: white;" href="{% url "post_page" post.slug %}">{{post.title}}</a>
          </p>
          {% endfor %} 
        </div>
      </div>
    </section>
{% endblock content %}

posts/templates/posts/create_post.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="container">
        <div class="page-name">
            <a href="{% url 'profile' %}" class="learn">
                <span class="material-icons">keyboard_return</span> Go back
            </a>
            <h2>Create Post</h2>
        </div>

        <form method="post" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Title:</label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_content">Content:</label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label for="id_image">Image (optional):</label>
                {{ form.image }}
            </div>
            <div class="form-group">
                <label for="id_tags">Tags:</label>
                {{ form.tags }}
            </div>
            <button type="submit" class="post-button">Submit</button>
        </form>
    </div>
</main>
{% endblock %}

posts/templates/posts/delete_post.html
{% extends "base.html" %}
{% block title %}Delete Post{% endblock title %}

{% block content %}
<main>
    <div class="container">
        <div class="page-name">
            <a href="{% url 'post_page' post.slug %}" class="learn">
                <span class="material-icons">keyboard_return</span> Go back
            </a>
            <h2>Delete Post</h2>
        </div>

        <div class="cardx">
            <div class="card-body">
                <p class="confirmation-message"><b>Are you sure you want to delete the post?</b></p>
                <form method="post">
                    {% csrf_token %}
                    <div class="update">
                        <div class="update-container">
                            <button type="submit" class="btn btn-primary">Yes, delete</button>
                            <a href="{% url 'post_page' post.slug %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

posts/templates/posts/edit_post.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="container">
        <div class="page-name">
            <a href="#" class="learn" onclick="window.history.back()">
                <span class="material-icons">keyboard_return</span> Go back
            </a>
            <h2>Edit Post</h2>
        </div>

        <div class="cardx">
            <div class="card-body" style="font-size: 18px; font-weight:bold;">
                <form method="post" enctype="multipart/form-data" class="post-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Title:</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="id_content">Content:</label>
                        {{ form.content }}
                    </div>
                    <div class="form-group">
                        <label for="id_image">Image (optional):</label>
                        {{ form.image }}
                    </div>
                    <div class="form-group">
                        <label for="id_tags">Tags:</label>
                        {{ form.tags }}
                    </div>
                    <button type="submit" class="post-button">Update</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

posts/templates/posts/search.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blog | Search{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="#" class="learn" onclick="window.history.back()">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>Search</h1>
            </div>
            <form class="search-bar s-active" method="GET">
              <input type="text" placeholder="Search" name="q" value="{{search_query}}"/>
              <button type="submit" class="animated-search">
                <i class="uil uil-search"></i>
              </button>
            </form>
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
        <div class="grid">
          <!-- card -->
          {% for post in posts %}
          <a href="{% url "post_page" post.slug %}">
            <div class="card">
              <div class="post-img">
                <img src="{{post.image.url}}" alt="" />
                {% if post.tags.all %}
                <div class="tag">{{ post.tags.all.0.name }}</div>
                {% endif %}
              </div>
              <div class="card-content">
                <h3>{{ post.title }}</h3>
                <div class="author">
                  <div class="profile-pic">
                    {% if post.author.profile.profile_image %}
                    <img src="{{post.author.profile.profile_image.url}}" alt="" />
                    {% else %}
                    <img src="{% static "images/blank-profile.webp" %}" alt="blank Image">
                    {% endif %}
                  </div>
                  <div class="details">
                    <p>{{ post.author.profile.full_name }}</p>
                    <small>{{ post.last_updated|date }}</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
          {% endfor %}
          <!-- card end-->
        </div>
      </div>
    </section>

    <!-- Pagination -->
    <div class="container">
      <div class="pagination">
        {% if posts.has_previous %}
          <a href="?page=1">&laquo;</a>
          <a href="?page={{ posts.previous_page_number }}">{{ posts.previous_page_number }}</a>
        {% endif %}
        
        <span class="current">{{ posts.number }}</span>

        {% if posts.has_next %}
          <a href="?page={{ posts.next_page_number }}">{{ posts.next_page_number }}</a>
          <a href="?page={{ posts.paginator.num_pages }}">&raquo;</a>
        {% endif %}
      </div>
    </div>
{% endblock content %}

posts/templates/posts/tag_all_posts.html
{% extends "base.html" %} 
{% block title %}Blog | {{tag.name}}{% endblock title %}

{% block content %}
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="#" class="learn" onclick="window.history.back()">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>All posts with tag {{tag.name}}</h1>
            </div>
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
        <div class="blog-tags">
          {% for post in all_posts %}
          <p class="tag">
            <a style="color: white;" href="{% url "post_page" post.slug %}">{{post.title}}</a>
          </p>
          {% endfor %} 
        </div>
      </div>
    </section>
{% endblock content %}